version: '3.8'

services:
  wealth-tracker:
    image: nicejade/wealth-tracker
    container_name: wealth-tracker
    ports:
      - '8888:8888'
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  data:
